# Generated by Django 4.0 on 2022-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoriasProd',
            field=models.ManyToManyField(to='tienda.CategoriaProducto'),
        ),
    ]
