# Generated by Django 4.0 on 2022-04-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_categoriaproducto_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='../proyectoWebApp/static/proyectoWebApp/img/img-no-disponible.jpeg', upload_to='tienda'),
        ),
    ]
