# Generated by Django 4.0 on 2022-04-20 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=datetime.datetime(2022, 4, 20, 5, 48, 5, 495815, tzinfo=utc), upload_to='tienda'),
            preserve_default=False,
        ),
    ]
