# Generated by Django 4.0 on 2022-04-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_created_categoria_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='../proyectoWebApp/static/proyectoWebApp/img/img-no-disponible.jpeg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
